name: Build And Publish

on: push

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
      API_SERVER_URL: ${{ secrets.API_SERVER_URL }}
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build:demo
      - run: cp ./dist/spa_angular_typescript_hello-world/index.html ./dist/spa_angular_typescript_hello-world/404.html # Rewrite du pauvre pour Github Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist/spa_angular_typescript_hello-world/

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
